### PR TITLE
fix: limit nested node selections to 3 items

### PR DESCRIPTION
**Pull request by yyyyaaa**
cc @pyramation please review this

### CODE REVIEW

**Comment by yyyyaaa** [comment]
Actually don't merge this just yet

**Comment by yyyyaaa** [comment]
@pyramation hi I think you can merge this, please review for me :)

**Comment by yyyyaaa** [comment]
I was having a seemingly weird idea: instead of returning 3 nodes for each nested field, we just return the info for further fetching, something like
```
actionGoals {
  __query: "getActionGoals",
  __queryParams: {
    parentId: "abc",
  }
}
```

**Comment by yyyyaaa** [comment]
and then for each row that will need this info, we will actually use the `__query` bit when the column `actionGoals` is expanded, or focused

**Comment by pyramation** [comment]
merged! that's a cool idea! let's talk about it soon

**Comment by pyramation** [comment]
```
Successfully published:
 - graphile-gen-sql@0.3.2
 - graphile-gen@0.3.8
 - @pyramation/graphql-ast@0.2.0
lerna success published 3 packages
```

**Pull request merged**
